# Generated by Django 4.0.3 on 2022-11-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
