# Generated by Django 4.0.3 on 2022-11-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_location_lat_location_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weather_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
