# Generated by Django 4.0.3 on 2022-11-11 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_location_temperature_location_weather_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='temperature',
            new_name='temp',
        ),
    ]
