# Generated by Django 4.0.3 on 2022-11-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_conference_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='temp',
        ),
    ]
